services:
    Ntriga\PimcoreSeoBundle\Controller\:
        resource: '../../src/Controller'
        public: true
        autowire: true
        autoconfigure: true
        tags: ['controller.service_arguments']
