services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Ntriga\PimcoreSeoBundle\Tool\Install:
        arguments:
            $bundle: "@=service('kernel').getBundle('NtrigaPimcoreSeoBundle')"
