services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    seo.application_logger.seo_logger:
        public: true
        class: Pimcore\Bundle\ApplicationLoggerBundle\ApplicationLogger
        calls:
           - [addWriter, ['@Pimcore\Bundle\ApplicationLoggerBundle\Handler\ApplicationLoggerDb']]
           - [setComponent, ['seo-bundle']]

    Ntriga\PimcoreSeoBundle\Logger\LoggerInterface: '@Ntriga\PimcoreSeoBundle\Logger\Logger'
    Ntriga\PimcoreSeoBundle\Logger\Logger:
        arguments:
            - '@seo.application_logger.seo_logger'

