services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ntriga\PimcoreSeoBundle\Repository\QueueEntryRepositoryInterface: '@Ntriga\PimcoreSeoBundle\Repository\QueueEntryRepository'
    Ntriga\PimcoreSeoBundle\Repository\QueueEntryRepository: ~

    Ntriga\PimcoreSeoBundle\Repository\ElementMetaDataRepositoryInterface: '@Ntriga\PimcoreSeoBundle\Repository\ElementMetaDataRepository'
    Ntriga\PimcoreSeoBundle\Repository\ElementMetaDataRepository: ~
