services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ntriga\PimcoreSeoBundle\Tool\LocaleProviderInterface: '@Ntriga\PimcoreSeoBundle\Tool\LocaleProvider'
    Ntriga\PimcoreSeoBundle\Tool\LocaleProvider: ~
