services:
    _defaults:
      autowire: true
      autoconfigure: true
      public: false

    Ntriga\PimcoreSeoBundle\Twig\Extension\SeoExtension:
        tags:
          - { name: twig.extension }
