doctrine:
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        entity_managers:
            default:
                auto_mapping: true

doctrine_migrations:
    migrations_paths:
        'Ntriga\PimcoreSeoBundle\Migrations': '@PimcoreSeoBundle/src/Migrations'
