# Admin routes
NtrigaSeo.controller.admin.meta-data.get_meta_data_definitions:
  path: /admin/ntrigaseo/meta-data/get-meta-data-definitions
  defaults: { _controller: Ntriga\PimcoreSeoBundle\Controller\Admin\MetaDataController::getMetaDataDefinitionsAction }
